version: 2
multi-ecosystem-groups:
  group-everything:
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"

updates:
  - package-ecosystem: "pub"
    directory: "/"
    multi-ecosystem-group: "group-everything"

  - package-ecosystem: "gradle"
    directory: "/android"
    multi-ecosystem-group: "group-everything"

  - package-ecosystem: "swift"
    directory: "/ios"
    multi-ecosystem-group: "group-everything"
